# [[custom_groups]]
# name = "Auto"
# type = "url-test"
# rule = [".*"]
# url = "http://www.gstatic.com/generate_204"
# interval = 300
# tolerance = 150
# lazy = true

# [[custom_groups]]
# name = "Proxy"
# type = "select"
# rule = [".*", "[]DIRECT"]
# disable_udp = false

# [[custom_groups]]
# name = "LoadBalance"
# type = "load-balance"
# rule = [".*", "[]Proxy", "[]DIRECT"]
# interval = 100
# strategy = "consistent-hashing"
# url = "http://www.gstatic.com/generate_204"

[[custom_groups]]
name = "ğŸŒ Proxynd"
type = "select"
rule = ["!!GROUPID=0!!(å¹¿æ¸¯IEPLS)", "!!GROUPID=1!!(é¦™æ¸¯ISL$|å°æ¹¾|æ–°åŠ å¡)"]

[[custom_groups]]
name = "ğŸ’ SocialM"
type = "select"
rule = ["!!GROUPID=0!!(æ²ªæ—¥IPLC)", "!!GROUPID=1!!(æ—¥æœ¬)"]

[[custom_groups]]
name = "ğŸ”® GoogleÂ®"
type = "select"
rule = ["!!GROUPID=0!!(å¹¿æ¸¯IEPLS)", "!!GROUPID=1!!(é¦™æ¸¯ISLN)"]

[[custom_groups]]
name = "ğŸ“º EmbyVip"
type = "select"
rule = ["!!GROUPID=0!!(å¹¿æ¸¯IEPL$|azhk)", "[]DIRECT"]

[[custom_groups]]
name = "ğŸ¥ EmbyDmm"
type = "select"
rule = ["!!GROUPID=0!!(æ²ªéŸ©|æ²ªæ—¥IEPL)"]

[[custom_groups]]
name = "ğŸ“½ï¸ NetFlix"
type = "select"
rule = ["!!GROUPID=2!!(æ‡’äºº|æ–°åŠ å¡|å°æ¹¾)"]
