# [[rulesets]]
# group = ""
# ruleset = ""
# type = "surge-ruleset"
# interval = 86400

[[rulesets]]
group = "ğŸŒ Proxynd"
ruleset = "https://raw.githubusercontent.com/xiaochong113/bypass/master/rules/Common.yaml"
type = "clash-classic-ruleset"
interval = 86400

[[rulesets]]
group = "ğŸŒ Proxynd"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.yaml"
type = "clash-classic-ruleset"
interval = 86400

[[rulesets]]
group = "ğŸŒ Proxynd"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.yaml"
type = "clash-classic-ruleset"
interval = 86400

[[rulesets]]
group = "ğŸ’ SocialM"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.yaml"
type = "clash-classic-ruleset"
interval = 86400

[[rulesets]]
group = "ğŸ’ SocialM"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Instagram/Instagram.yaml"
type = "clash-classic-ruleset"
interval = 86400

[[rulesets]]
group = "ğŸ’ SocialM"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Twitter/Twitter.yaml"
type = "clash-classic-ruleset"
interval = 86400

[[rulesets]]
group = "ğŸ”® GoogleÂ®"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.yaml"
type = "clash-classic-ruleset"
interval = 86400

[[rulesets]]
group = "ğŸ”® GoogleÂ®"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.yaml"
type = "clash-classic-ruleset"
interval = 86400

[[rulesets]]
group = "ğŸ“º EmbyVip"
ruleset = "https://raw.githubusercontent.com/xiaochong113/bypass/master/rules/EmbyVip.yaml"
type = "clash-classic-ruleset"
interval = 86400

[[rulesets]]
group = "ğŸ¥ EmbyDmm"
ruleset = "https://raw.githubusercontent.com/xiaochong113/bypass/master/rules/EmbyDmm.yaml"
type = "clash-classic-ruleset"
interval = 86400

[[rulesets]]
group = "ğŸ“½ï¸ NetFlix"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.yaml"
type = "clash-classic-ruleset"
interval = 86400

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/xiaochong113/bypass/master/rules/direct.yaml"
type = "clash-classic-ruleset"
interval = 86400

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Download/Download.yaml"
type = "clash-classic-ruleset"
interval = 86400

[[rulesets]]
group = "REJECT"
ruleset = "https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/Guard/Hijacking.list"
type = "clash-classic-ruleset"
interval = 86400

[[rulesets]]
group = "REJECT"
ruleset = "https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/Guard/Advertising.list"
type = "clash-classic-ruleset"
interval = 86400

[[rulesets]]
group = "REJECT"
ruleset = "https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/Guard/Privacy.list"
type = "clash-classic-ruleset"
interval = 86400

[[rulesets]]
group = "DIRECT"
ruleset = "[]GEOIP,CN"

[[rulesets]]
group = "ğŸŒ Proxynd"
ruleset = "[]MATCH"
